name: Windows
on: [push, pull_request]

jobs:
  main:
    name: main
    runs-on: windows-${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - '2016'
        python-version:
          - '2.7'
#          - '3.6'
#          - '3.7'
      fail-fast: false
#    env:
#      PATH: C:\Program Files\PowerShell\6\;${ENV:SystemRoot}\system32;${ENV:SystemRoot};${ENV:SystemRoot}\System32\Wbem;${ENV:SYSTEMROOT}\System32\WindowsPowerShell\v1.0\
    env:
      PATH: c:\users\runner~1\appdata\local\temp\rez_selftest_mtsn0c\packages\hello_world\1.0/bin;C:\Program Files\PowerShell\6\;C:/hostedtoolcache/windows\Python\3.6.8\x64;C:\windows;C:\hostedtoolcache\windows\Python\3.7.4\x64\Scripts;C:/hostedtoolcache/windows\Python\3.6.8\x64\Scripts;C:\Program Files\OpenSSL\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Mercurial\;C:\windows\System32\Wbem;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\windows\System32\OpenSSH\;C:\Program Files\Git\bin;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\system32;C:\Program Files\CMake\bin;C:\Users\runneradmin\.dotnet\tools;C:\Program Files\Git\usr\bin;C:\hostedtoolcache\windows\Python\3.7.4\x64;

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Reduce PATH variables
        run: |
          echo "PATH Length: " ${ENV:PATH}.Length
          echo "PATH Length: " ${ENV:PATH}.Length
          echo $Env:PATH
#          cmd /c setx /m PATH "C:\Program Files\PowerShell\6\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\"
#          ${ENV:PATH} = "C:\Program Files\PowerShell\6\;${ENV:SystemRoot}\system32;${ENV:SystemRoot};${ENV:SystemRoot}\System32\Wbem;${ENV:SYSTEMROOT}\System32\WindowsPowerShell\v1.0\"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify cmake
        run: |
          cmake.exe --version

      - name: Verify pwsh
        run: |
          pwsh --version

      - name: Install Rez
        run: |
          mkdir build
          python install.py build

      - name: Run Rez Tests
        run: |
          .\build\Scripts\rez\rez-selftest.exe
